---
title: "R Notebook"
output: html_notebook
---

```{r, include=false}
library(lubridate) # deal with dates
library(dplyr) #organise data
library(tidyr) #organise data
library(ggplot2) # graph
library(zoo) # na approx?
```

```{r}
#comment
TrialDesign_raw <- read.table("C:/GitHubRepos/BarleyPAR/TrialDesign.txt",header = TRUE)

# check
summary(TrialDesign_raw)
```
```{r}
# using dplyr
TrialDesign_work <- TrialDesign_raw %>%
  mutate(Plot=factor(Plot))%>% # make it as a date format (not a factor
   mutate(Block=factor(Block)) # make it as a date format (not a factor)
str(TrialDesign_work)   
```

# read total radiation
```{r}
#comment
data_Rad_raw <- read.table("C:/GitHubRepos/BarleyPAR/TotalRadiation.txt",header = TRUE)

# check
summary(data_Rad_raw)
```
```{r}
# using dplyr
data_Rad_work <- data_Rad_raw %>%
  mutate(Date=dmy(Date)) # make it as a date format (not a factor)
   
str(data_Rad_work)   

  
```

```{r}
summary(data_Rad_work)
```

# read_data
## heading
this is text to document
## SunScan ----------------

```{r}
#comment
data_sun_raw <- read.table("C:/GitHubRepos/BarleyPAR/SunScan.txt",header = TRUE)

# check
summary(data_sun_raw)
```

```{r}
# check formats
str(data_sun_raw)
```


# clean data

```{r}
# using dplyr
data_sun_work <- data_sun_raw %>%
  mutate(Date=dmy(Date)) %>% # make it as a date format (not a factor)
   mutate(Plot=factor(Plot)) %>%# make it a factor (i.e. not number)
   mutate(SunScan = ifelse(SunScan<0,0,SunScan))

str(data_sun_work)    
  
```



```{r}
summary(data_sun_work)
```

## Greenseeker ----------------

```{r}
#comment
data_GreenS_raw <- read.table("C:/GitHubRepos/BarleyPAR/GreenSeeker.txt",header = TRUE)

# check
summary(data_GreenS_raw)
```

```{r}
# check formats
str(data_GreenS_raw)
```


# clean data

```{r}
# using dplyr
data_GreenS_work <- data_GreenS_raw %>%
  mutate(Date=dmy(Date)) %>% # make it as a date format (not a factor)
   mutate(Plot=factor(Plot)) %>%# make it a factor (i.e. not number)
   mutate(GreenSeeker = ifelse(GreenSeeker<0,0,GreenSeeker))

str(data_GreenS_work)    
  
```
```{r}
summary(data_GreenS_work)
```

# 2. Interpolate values by day

```{r}
stDate <- dmy("14/10/2014") # sowing date
endate <- dmy("11/02/2015") # harvest date  
plotNo <- c(201:224)

df_frame <- data_Rad_work %>%
  filter(Date %in% stDate:endate) %>%
  mutate(Plot=NA) # create empty variable

summary(df_frame)

df_all <- data.frame()

for(i in 1:length(plotNo)) {
  
  df_this <- df_frame %>% mutate(Plot = plotNo[i]) # creates plot # as i index from plotNo
  
  df_all <- rbind(df_all,df_this)
  
}

summary(df_all)

# merge with data but keep NAs for dates when no measurement was done # FIXME: do it elegantly later
df_temp <- merge(df_all, data_GreenS_work,by=c("Date","Plot"), all=T)
df_temp2 <- merge(df_temp, data_sun_work,by=c("Date","Plot"), all=T)

df_temp3 <- df_temp2 %>% 
  mutate(GreenSeeker= ifelse(Date==stDate,0,GreenSeeker)) %>%
  mutate(SunScan= ifelse(Date==stDate,0,SunScan)) %>%
  mutate(GreenSeeker= ifelse(Date==endate,0,GreenSeeker)) %>%
  mutate(SunScan= ifelse(Date==endate,0,SunScan)) 



```

```{r}
options(scipen=999)

# create interpolated df
df_interpolated <- df_temp3 %>%
 group_by(Plot) %>%
 arrange(Plot, Date) %>%
 mutate(GreenSeeker_Int = na.approx(GreenSeeker, na.rm=FALSE)) %>%
 mutate(SunScan_Int = na.approx(SunScan, na.rm=FALSE)) %>%
 mutate(RadInt_GS = GreenSeeker_Int*Radiation, RadInt_SS = SunScan_Int*Radiation) %>%
 mutate(RadInt_GS_sum = cumsum(RadInt_GS)) %>%
 mutate(RadInt_SS_sum=cumsum(RadInt_SS)) %>%
 merge(TrialDesign_work, by=("Plot"))  

summary(df_interpolated)
```

```{r}
df_interpolated %>%
 # tidyr::gather("variable","Value",RadInt_GS_sum:RadInt_SS_sum) %>%
  ggplot(aes(x=Date, y=RadInt_GS_sum, colour=Block)) +
  geom_point() +
  facet_grid(Cultivar~Irrigation)
```

```{r}
df_interpolated %>%
 # tidyr::gather("variable","Value",RadInt_GS_sum:RadInt_SS_sum) %>%
  ggplot(aes(x=Date, y=RadInt_GS_sum, colour=Block)) +
  geom_point() +
  facet_grid(Cultivar~Irrigation)
```

```{r}
df_interpolated %>%
 # tidyr::gather("variable","Value",RadInt_GS_sum:RadInt_SS_sum) %>%
  ggplot(aes(x=Date, y=RadInt_SS_sum, colour=Block)) +
  geom_point() +
  facet_grid(Cultivar~Irrigation)
```
# Remove mid - irrigation and select columns of interest
```{r}
# list of column names we wann drop
drop.cols <- c("GreenSeeker", "SunScan", "GreenSeeker_Int", "SunScan_Int","RadInt_GS","RadInt_SS")
keep.plots <- c("202","204", "205", "206", "210", "213", "215", "217", "219", "220", "221", "222")

# do the filtering
df_spot <- df_interpolated %>%
  filter(Plot %in% keep.plots) %>% # keeping plots
  dplyr::select(-one_of(drop.cols)) # removing columns

# do a test
print(length(unique(df_spot$Plot)))

```
```{r}
write.table(df_spot, "C:/GitHubRepos/BarleyPAR/AccRad_cepSun.txt")
```

